monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.*DELL_Slim_Soundbar_SB522A.*"
      }
    ]
    actions = {
      update-props = {
        node.priority.session = 2000
      }
    }
  }
]
