#!/bin/sh

# Load Configs
source "$CONFIG_DIR/config/config.sh"
source "$CONFIG_DIR/config/styles.sh"

# Basic Bar Setup
sketchybar --bar "${bar[@]}"
sketchybar --default "${default[@]}"

# Setup Bar Items
source "$CONFIG_DIR/config/setup_spaces.sh"
source "$CONFIG_DIR/config/setup_left_items.sh"
source "$CONFIG_DIR/config/setup_right_items.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
