#!/bin/sh

# Load Configs
source "$CONFIG_DIR/config/config.sh"
source "$CONFIG_DIR/config/colors.sh"
source "$CONFIG_DIR/config/styles.sh"

# Basic Bar Setup
sketchybar --bar "${bar[@]}"
sketchybar --default "${default[@]}"

# Setup Bar Items
source "$CONFIG_DIR/items/logo.sh"
source "$CONFIG_DIR/items/aerospace.sh"
source "$CONFIG_DIR/items/front_app.sh"
source "$CONFIG_DIR/config/setup_right_items.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
